# Generated by Django 6.0.7 on 2026-07-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='action',
        ),
        migrations.AddField(
            model_name='history',
            name='case_action',
            field=models.CharField(choices=[('F', 'Followed Up'), ('C', 'Closed')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='suspect',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='victim',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='victim',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
