# Generated by Django 6.0.7 on 2026-07-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyz', '0002_remove_history_action_history_case_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='case_action',
            field=models.CharField(choices=[('u', 'Followed Up'), ('C', 'Closed'), ('F', 'Finished')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='stolenitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stolenitem',
            name='values',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='m', max_length=1),
        ),
    ]
