# Generated by Django 6.0.7 on 2026-07-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyz', '0003_alter_history_case_action_alter_stolenitem_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='case_action',
            new_name='action',
        ),
    ]
