# Generated by Django 6.0.7 on 2026-07-15 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyz', '0004_rename_case_action_history_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigationreport',
            old_name='office_name',
            new_name='officer',
        ),
        migrations.RenameField(
            model_name='policecenter',
            old_name='police_name',
            new_name='police_officer',
        ),
        migrations.RemoveField(
            model_name='history',
            name='perfomed_by',
        ),
        migrations.RemoveField(
            model_name='stolenitem',
            name='values',
        ),
        migrations.AddField(
            model_name='history',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xyz.policeofficer'),
        ),
        migrations.AddField(
            model_name='stolenitem',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('Followed Up', 'Followed Up'), ('Closed', 'Closed'), ('Finished', 'Finished')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stolenitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='theftcase',
            name='case_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='theftcase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='theftcase',
            name='suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xyz.suspect'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
