# Generated by Django 6.0.7 on 2026-07-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyz', '0005_rename_office_name_investigationreport_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theftcase',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'Investigating'), ('R', 'Resolved'), ('C', 'Closed')], default='P', max_length=20),
        ),
    ]
