# Generated by Django 6.0.7 on 2026-07-16 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyz', '0006_alter_theftcase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationreport',
            name='report',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='theftcase',
            name='reported_at',
            field=models.DateTimeField(default='2026-01-01'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='theft_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='xyz.theftcase'),
        ),
        migrations.AlterField(
            model_name='history',
            name='theft_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='xyz.theftcase'),
        ),
        migrations.AlterField(
            model_name='investigationreport',
            name='theft_case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_report', to='xyz.theftcase'),
        ),
        migrations.AlterField(
            model_name='policecenter',
            name='police_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='xyz.policeofficer'),
        ),
        migrations.AlterField(
            model_name='policeofficer',
            name='badge_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stolenitem',
            name='theft_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stolen_items', to='xyz.theftcase'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='theftcase',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='xyz.policeofficer'),
        ),
        migrations.AlterField(
            model_name='theftcase',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='theftcase',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('I', 'Investigating'), ('R', 'Resolved'), ('C', 'Closed')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='theftcase',
            name='suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='xyz.suspect'),
        ),
        migrations.AlterField(
            model_name='theftcase',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='xyz.victim'),
        ),
        migrations.AlterField(
            model_name='victim',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='witness',
            name='theft_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='xyz.theftcase'),
        ),
    ]
