# Generated by Django 6.0.7 on 2026-07-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyz', '0007_investigationreport_report_theftcase_reported_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='national_id',
            field=models.CharField(default=0, max_length=30, unique=True),
        ),
    ]
