# Generated by Django 6.0.7 on 2026-07-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyz', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('police', 'Police'), ('admin', 'Admin'), ('policymaker', 'Policy Maker'), ('aker', 'Aker')], max_length=20),
        ),
        migrations.AlterField(
            model_name='victim',
            name='national_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
