# Generated by Django 6.0.7 on 2026-07-14 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_number', models.CharField(max_length=100, unique=True)),
                ('station', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=100)),
                ('office_name', models.CharField(max_length=100)),
                ('police_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xyz.policeofficer')),
            ],
        ),
        migrations.CreateModel(
            name='TheftCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField()),
                ('incident_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xyz.policeofficer')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xyz.suspect')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xyz.victim')),
            ],
        ),
        migrations.CreateModel(
            name='StolenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('values', models.IntegerField()),
                ('theft_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xyz.theftcase')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('office_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xyz.policeofficer')),
                ('theft_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xyz.theftcase')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_collected', models.DateTimeField(auto_now_add=True)),
                ('theft_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xyz.theftcase')),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('statement', models.TextField()),
                ('theft_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xyz.theftcase')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('theft_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xyz.theftcase')),
                ('perfomed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xyz.witness')),
            ],
        ),
    ]
