# Generated by Django 6.0.7 on 2026-07-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyz', '0008_victim_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theftcase',
            name='reported_at',
            field=models.DateTimeField(),
        ),
    ]
